/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/car.glb --transform 
Files: assets/car.glb [777.21KB] > /Users/justin/Documents/Documents - Justin's MacBook Pro/Education/4-1/thesis/app/safeseat-app/car-transformed.glb [82.36KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3d-model'].geometry} material={materials['0136_Charcoal']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/car-transformed.glb')
