/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/car.glb -o src/components/CarModel.js 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['3d-model_1'].geometry} material={materials['0136_Charcoal']} />
        <mesh geometry={nodes['3d-model_2'].geometry} material={materials.Matte__FF1} />
        <mesh geometry={nodes['3d-model_3'].geometry} material={materials.Matte__FFA08B5F1} />
        <mesh geometry={nodes['3d-model_4'].geometry} material={materials.Matte__FF5B5B5B1} />
        <mesh geometry={nodes['3d-model_5'].geometry} material={materials.Matte__FFFF1} />
        <mesh geometry={nodes['3d-model_6'].geometry} material={materials.Matte__FF5} />
        <mesh geometry={nodes['3d-model_7'].geometry} material={materials._Charcoal_} />
        <mesh geometry={nodes['3d-model_8'].geometry} material={materials['0128_White']} />
        <mesh geometry={nodes['3d-model_9'].geometry} material={materials['001__spec_1']} />
        <mesh geometry={nodes['3d-model_10'].geometry} material={materials['0020_Red']} />
        <mesh geometry={nodes['3d-model_11'].geometry} material={materials['0131_Silver']} />
        <mesh geometry={nodes['3d-model_12'].geometry} material={materials.preto__spec_1} />
        <mesh geometry={nodes['3d-model_13'].geometry} material={materials.Rubber_Plastic1} />
        <mesh geometry={nodes['3d-model_14'].geometry} material={materials.Light_White_Reflective} />
        <mesh geometry={nodes['3d-model_15'].geometry} material={materials.Plastic_Silver} />
        <mesh geometry={nodes['3d-model_16'].geometry} material={materials.skp_front_default} />
        <mesh geometry={nodes['3d-model_17'].geometry} material={materials['0137_Black']} />
        <mesh geometry={nodes['3d-model_18'].geometry} material={materials['0076_Green']} />
        <mesh geometry={nodes['3d-model_19'].geometry} material={materials.Material8} />
        <mesh geometry={nodes['3d-model_20'].geometry} material={materials['0022_Maroon']} />
        <mesh geometry={nodes['3d-model_21'].geometry} material={materials.jean_blue} />
        <mesh geometry={nodes['3d-model_22'].geometry} material={materials.brakes} />
        <mesh geometry={nodes['3d-model_23'].geometry} material={materials.Material1} />
        <mesh geometry={nodes['3d-model_24'].geometry} material={materials['96_96_96']} />
        <mesh geometry={nodes['3d-model_25'].geometry} material={materials['0135_DarkGray']} />
      </group>
    </group>
  )
}

useGLTF.preload('/car.glb')
