import { FontSize as fontsize, Spacing as spacing, type ThemePalette } from "@/constants/theme";
import { useTheme } from "@/hooks/use-theme";
import * as Haptics from "expo-haptics";
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

type WindowValue=20|25|30; type Props={value:WindowValue;enabled?:boolean;onValueChange:(v:WindowValue)=>void}; const VALUES:WindowValue[]=[20,25,30];
export default function EscalationWindowControl({value,enabled=true,onValueChange}:Props){const themes=useTheme();const styles=createStyles(themes);const[trackWidth,setTrackWidth]=useState(1);const index=VALUES.indexOf(value);const percent=index<=0?0:index===1?50:100;const select=(n:WindowValue)=>{if(!enabled||n===value)return;void Haptics.selectionAsync();onValueChange(n)};const handle=(x:number)=>{const r=Math.max(0,Math.min(1,x/trackWidth));select(r<.25?20:r<.75?25:30)};return <View style={[styles.card,!enabled&&{opacity:.45}]}><View style={styles.header}><View style={{flex:1}}><Text style={styles.title}>Driver SMS Delay</Text><Text style={styles.sub}>Time to cancel a confirmed Driver-seat emergency before automated SMS becomes eligible.</Text></View><View style={styles.badge}><Text style={styles.value}>{value}s</Text></View></View><Pressable accessibilityRole="adjustable" disabled={!enabled} onLayout={e=>setTrackWidth(e.nativeEvent.layout.width)} onPress={e=>handle(e.nativeEvent.locationX)} style={{paddingVertical:10}}><View style={styles.track}><View style={[styles.active,{width:`${percent}%`}]} />{[0,50,100].map(p=><View key={p} style={[styles.stop,{left:`${p}%`}]} />)}<View style={[styles.thumb,{left:`${percent}%`}]} /></View></Pressable><View style={styles.labels}>{VALUES.map(v=><Pressable key={v} onPress={()=>select(v)} disabled={!enabled} hitSlop={8}><Text style={[styles.label,v===value&&styles.selected]}>{v}s</Text></Pressable>)}</View></View>}
const createStyles=(t:ThemePalette)=>StyleSheet.create({card:{backgroundColor:t.backgroundElement,borderRadius:18,borderWidth:1,borderColor:t.divider,padding:spacing.two,gap:spacing.two},header:{flexDirection:"row",alignItems:"center",gap:10},title:{color:t.text,fontSize:fontsize.body,fontFamily:"Body-Bold"},sub:{color:t.textSecondary,fontSize:fontsize.caption,lineHeight:20,marginTop:3,fontFamily:"Body-Regular"},badge:{minWidth:58,paddingHorizontal:10,paddingVertical:6,alignItems:"center",borderRadius:999,backgroundColor:t.primarySoft,borderWidth:1,borderColor:t.primaryBorder},value:{color:t.primaryBttn,fontSize:fontsize.body,fontFamily:"Body-Bold"},track:{height:7,borderRadius:999,backgroundColor:t.secondaryBttn,position:"relative"},active:{position:"absolute",left:0,top:0,bottom:0,borderRadius:999,backgroundColor:t.primaryBttn},stop:{position:"absolute",width:11,height:11,marginLeft:-5.5,marginTop:-2,borderRadius:6,backgroundColor:t.backgroundElevated,borderWidth:2,borderColor:t.textSecondary},thumb:{position:"absolute",width:24,height:24,marginLeft:-12,marginTop:-8.5,borderRadius:12,backgroundColor:t.primaryBttn,borderWidth:3,borderColor:t.backgroundElement},labels:{flexDirection:"row",justifyContent:"space-between"},label:{color:t.textMuted,fontSize:fontsize.caption,fontFamily:"Body-Medium"},selected:{color:t.primaryBttn,fontFamily:"Body-Bold"}});
